-- ============================================================
-- PERKESO Bulletin Dashboard — Seed Data
-- Run this in the Supabase SQL Editor AFTER schema.sql
-- All passwords are MOCK/dummy for prototype only (per BRS §9.1)
-- ============================================================

BEGIN;

-- Users
INSERT INTO "User" ("id","email","name","password","role","department","branch","position","avatarUrl","isActive","createdAt","updatedAt") VALUES ('usr000000000000000000000001', 'admin@perkeso.gov.my', 'Aisyah Binti Rahman', 'admin123', 'Admin', 'Bahagian Komunikasi Korporat', 'Ibu Pejabat Kuala Lumpur', 'Pegawai Komunikasi Korporat', 'https://i.pravatar.cc/150?img=47', true, NOW(), NOW());
INSERT INTO "User" ("id","email","name","password","role","department","branch","position","avatarUrl","isActive","createdAt","updatedAt") VALUES ('usr000000000000000000000002', 'staff@perkeso.gov.my', 'Mohammad Faizal Bin Osman', 'staff123', 'Staff', 'Bahagian Pampasan', 'Cawangan Pulau Pinang', 'Pegawai Pampasan', 'https://i.pravatar.cc/150?img=12', true, NOW(), NOW());
INSERT INTO "User" ("id","email","name","password","role","department","branch","position","avatarUrl","isActive","createdAt","updatedAt") VALUES ('usr000000000000000000000003', 'siti.noor@perkeso.gov.my', 'Siti Noor Aishah', 'staff123', 'Staff', 'Bahagian Perubatan', 'Cawangan Johor Bahru', 'Pegawai Perubatan', 'https://i.pravatar.cc/150?img=45', true, NOW(), NOW());
INSERT INTO "User" ("id","email","name","password","role","department","branch","position","avatarUrl","isActive","createdAt","updatedAt") VALUES ('usr000000000000000000000004', 'tan.wei@perkeso.gov.my', 'Tan Wei Ming', 'staff123', 'Staff', 'Bahagian Kewangan', 'Cawangan Ipoh', 'Pegawai Kewangan', 'https://i.pravatar.cc/150?img=15', true, NOW(), NOW());
INSERT INTO "User" ("id","email","name","password","role","department","branch","position","avatarUrl","isActive","createdAt","updatedAt") VALUES ('usr000000000000000000000005', 'ravi.kumar@perkeso.gov.my', 'Ravi Kumar a/l Subramaniam', 'staff123', 'Staff', 'Bahagian Teknologi Maklumat', 'Ibu Pejabat Kuala Lumpur', 'Jurutera Sistem', 'https://i.pravatar.cc/150?img=33', true, NOW(), NOW());
INSERT INTO "User" ("id","email","name","password","role","department","branch","position","avatarUrl","isActive","createdAt","updatedAt") VALUES ('usr000000000000000000000006', 'nurul.huda@perkeso.gov.my', 'Nurul Huda Binti Aziz', 'admin123', 'Admin', 'Bahagian Operasi', 'Ibu Pejabat Kuala Lumpur', 'Pengurus Operasi', 'https://i.pravatar.cc/150?img=49', true, NOW(), NOW());

-- Announcements
INSERT INTO "Announcement" ("id","title","category","summary","content","authorName","isPinned","isNew","isUrgent","attachments","coverColor","datePublished","createdAt","updatedAt") VALUES ('ann000000000000000000000001', 'Pengumuman Hari Kebangsaan PERKESO 2026', 'Korporat', 'Sambutan Hari Kebangsaan akan diadakan di semua cawangan PERKESO seluruh negara pada 31 Ogos 2026.', 'Bersempena sambutan Hari Kebangsaan ke-59, PERKESO akan mengadakan pelbagai aktiviti korporat di semua cawangan. Semua kakitangan dijemput menyertai perhimpunan dan acara budaya. Sila hadir berpakaian tradisional atau pakaian bertema ''Merdeka''. Majlis akan bermula jam 8:00 pagi.', 'Aisyah Binti Rahman', true, true, false, '[{"name":"Program_Merdeka_2026.pdf","type":"PDF","size":"1.2 MB"},{"name":"Senarai_Activiti.docx","type":"DOCX","size":"680 KB"}]', '#ED1C24', '2026-07-25T09:00:00Z', NOW(), NOW());
INSERT INTO "Announcement" ("id","title","category","summary","content","authorName","isPinned","isNew","isUrgent","attachments","coverColor","datePublished","createdAt","updatedAt") VALUES ('ann000000000000000000000002', 'Kemas Kini Sistem Caruman Bulanan PERKESO', 'ICT', 'Sistem caruman bulanan telah dinaik taraf dengan ciri e-pengesahan dan laporan pantas.', 'Sistem Pengurusan Caruman Bulanan (SPCB) versi 3.2 telah dilancarkan secara rasmi. Ciri baharu termasuk e-pengesahan dokumen, janaan laporan masa nyata, dan integrasi pejabat pos cawangan. Latihan pengguna akan diadakan setiap Khamis jam 2:00 petang secara dalam talian.', 'Nurul Huda Binti Aziz', false, true, false, '[{"name":"Manual_SPCB_v3.2.pdf","type":"PDF","size":"3.4 MB"}]', '#007DC5', '2026-07-22T14:30:00Z', NOW(), NOW());
INSERT INTO "Announcement" ("id","title","category","summary","content","authorName","isPinned","isNew","isUrgent","attachments","coverColor","datePublished","createdAt","updatedAt") VALUES ('ann000000000000000000000003', 'Cutian Umum Hari Buruh — Klinik Tutup', 'HR', 'Klinik PERKESO akan ditutup pada 1 Mei 2026 bersempena Hari Buruh.', 'Dimaklumkan bahawa semua klinik PERKESO di seluruh negara akan tutup pada 1 Mei 2026 (Hari Buruh). Rawatan kecemasan boleh dirujuk ke panel klinik berdekatan. Operasi akan kembali normal pada 2 Mei 2026.', 'Aisyah Binti Rahman', false, true, false, '[]', '#8DC63E', '2026-07-20T08:00:00Z', NOW(), NOW());
INSERT INTO "Announcement" ("id","title","category","summary","content","authorName","isPinned","isNew","isUrgent","attachments","coverColor","datePublished","createdAt","updatedAt") VALUES ('ann000000000000000000000004', 'AMARAN: Phishing E-mel Berpura-pura PERKESO', 'Kesihatan & Keselamatan', 'Dimaklumkan terdapat e-mel phishing yang berpura-pura dari PERKESO. Jangan klik pautan.', 'Pihak ICT telah menerima laporan bahawa terdapat e-mel phishing yang berpura-pura daripada PERKESO meminta maklumat log masuk. JANGAN klik sebarang pautan atau berikan maklumat peribadi. Laporkan segera ke soc@perkeso.gov.my. PERKESO tidak akan meminta kata laluan melalui e-mel.', 'Ravi Kumar a/l Subramaniam', true, true, true, '[{"name":"Panduan_Keselamatan.pdf","type":"PDF","size":"920 KB"}]', '#ED1C24', '2026-07-19T10:15:00Z', NOW(), NOW());
INSERT INTO "Announcement" ("id","title","category","summary","content","authorName","isPinned","isNew","isUrgent","attachments","coverColor","datePublished","createdAt","updatedAt") VALUES ('ann000000000000000000000005', 'Pertandingan Inovasi Kakitangan 2026', 'Korporat', 'Pendaftaran pertandingan inovasi kakitangan telah dibuka. Hadiah RM10,000.', 'PERKESO mengumumkan pertandingan inovasi kakitangan 2026 dengan tema ''Inovasi Untuk Rakyat''. Pendaftaran dibuka sehingga 15 Ogos 2026. Hadiah utama RM10,000 dan trofi. Penilaian berdasarkan kebolehgunaan, keberkesanan, dan impak operasi.', 'Nurul Huda Binti Aziz', false, false, false, '[{"name":"Borang_Penyertaan.docx","type":"DOCX","size":"420 KB"}]', '#F9BF10', '2026-07-10T09:00:00Z', NOW(), NOW());
INSERT INTO "Announcement" ("id","title","category","summary","content","authorName","isPinned","isNew","isUrgent","attachments","coverColor","datePublished","createdAt","updatedAt") VALUES ('ann000000000000000000000006', 'Kemas Kini Prosedur Tuntutan Pampasan Pekerja', 'Operasi', 'Prosedur tuntutan pampasan pekerja dikemas kini bagi mempercepat proses pengesahan.', 'Bermula 1 Ogos 2026, prosedur tuntutan pampasan pekerja akan dikemas kini dengan pengurangan masa pengesahan daripada 14 hari kepada 7 hari kerja. Borang baharu boleh dimuat turun dari modul SOP.', 'Mohammad Faizal Bin Osman', false, false, false, '[{"name":"Borang_Pampasan_v2.pdf","type":"PDF","size":"1.8 MB"}]', '#00C5AB', '2026-07-05T11:00:00Z', NOW(), NOW());
INSERT INTO "Announcement" ("id","title","category","summary","content","authorName","isPinned","isNew","isUrgent","attachments","coverColor","datePublished","createdAt","updatedAt") VALUES ('ann000000000000000000000007', 'Latihan Kesedaran Siber Keselamatan Wajib', 'Kesihatan & Keselamatan', 'Semua kakitangan diwajibkan hadir latihan kesedaran siber keselamatan.', 'Pihak pengurusan menetapkan bahawa semua kakitangan PERKESO wajib menghadiri latihan kesedaran siber keselamatan yang akan diadakan secara dalam talian. Slot boleh dipilih melalui portal latihan dalaman.', 'Ravi Kumar a/l Subramaniam', false, false, false, '[]', '#F27130', '2026-06-28T08:00:00Z', NOW(), NOW());
INSERT INTO "Announcement" ("id","title","category","summary","content","authorName","isPinned","isNew","isUrgent","attachments","coverColor","datePublished","createdAt","updatedAt") VALUES ('ann000000000000000000000008', 'Program Pensijilan ISO 27001 — Fasa 2', 'Korporat', 'PERKESO meneruskan program pensijilan ISO 27001 dengan audit fasa 2 pada September 2026.', 'Bahagian Kualiti & Keselamatan Maklumat akan menjalankan audit ISO 27001 fasa 2 pada September 2026. Semua jabatan diminta menyemak dan mengemaskini SOP berkaitan keselamatan maklumat sebelum 15 Ogos 2026.', 'Aisyah Binti Rahman', false, false, false, '[{"name":"Senarai_Semak_ISO27001.xlsx","type":"XLSX","size":"240 KB"}]', '#004E7A', '2026-06-20T09:30:00Z', NOW(), NOW());

-- Acts
INSERT INTO "Act" ("id","actNumber","title","category","description","fileName","fileSize","version","status","lastUpdated","createdAt","updatedAt") VALUES ('act000000000000000000000001', 'Akta 428', 'Akta Keselamatan Sosial Pekerja 1969', 'Akta Sosial', 'Akta utama yang menetapkan skim perlindungan sosial bagi pekerja Malaysia termasuk pampasan kemalangan, pension, dan invaliditi.', 'Akta_428_1969.pdf', '4.8 MB', 'Edisi 2026', 'Aktif', '2026-06-15T10:00:00Z', NOW(), NOW());
INSERT INTO "Act" ("id","actNumber","title","category","description","fileName","fileSize","version","status","lastUpdated","createdAt","updatedAt") VALUES ('act000000000000000000000002', 'Akta 799', 'Akta Sistem Insurans Pekerjaan 2017', 'Akta Insurans', 'Mewujudkan skim insurans pekerjaan bagi menganugerahkan faedah kepada pekerja yang mengalami kemalangan kerja atau penyakit pekerjaan.', 'Akta_799_2017.pdf', '3.2 MB', 'Edisi 2025', 'Aktif', '2026-05-20T12:00:00Z', NOW(), NOW());
INSERT INTO "Act" ("id","actNumber","title","category","description","fileName","fileSize","version","status","lastUpdated","createdAt","updatedAt") VALUES ('act000000000000000000000003', 'Akta 800', 'Akta Sistem Insurans Pekerjaan (Peraturan) 2017', 'Akta Insurans', 'Peraturan pelaksanaan Akta Sistem Insurans Pekerjaan 2017 mengenai tatacara pengurusan tuntutan dan pembayaran faedah.', 'Akta_800_2017.pdf', '1.6 MB', 'Edisi 2025', 'Aktif', '2026-04-12T09:00:00Z', NOW(), NOW());
INSERT INTO "Act" ("id","actNumber","title","category","description","fileName","fileSize","version","status","lastUpdated","createdAt","updatedAt") VALUES ('act000000000000000000000004', 'Akta 514', 'Akta Keselamatan dan Kesihatan Pekerjaan 1994', 'Akta Sosial', 'Mewujudkan rangka kerja perundangan bagi memastikan keselamatan, kesihatan, dan kebajikan pekerja di tempat kerja.', 'Akta_514_1994.pdf', '2.4 MB', 'Edisi 2024', 'Digantungan', '2025-11-10T10:00:00Z', NOW(), NOW());
INSERT INTO "Act" ("id","actNumber","title","category","description","fileName","fileSize","version","status","lastUpdated","createdAt","updatedAt") VALUES ('act000000000000000000000005', 'Akta 265', 'Akta Kilang dan Jentera 1967', 'Peraturan', 'Mengawal selia keselamatan kilang, jentera, dan pekerja industri.', 'Akta_265_1967.pdf', '1.9 MB', 'Edisi 2023', 'Digantikan', '2025-08-15T11:30:00Z', NOW(), NOW());
INSERT INTO "Act" ("id","actNumber","title","category","description","fileName","fileSize","version","status","lastUpdated","createdAt","updatedAt") VALUES ('act000000000000000000000006', 'Akta 139', 'Akta Kerja 1955', 'Peraturan', 'Akta yang mengawal selia hubungan majikan-pekerja, termasuk waktu kerja, cuti, dan upah.', 'Akta_139_1955.pdf', '3.8 MB', 'Edisi 2026 (Pindaan)', 'Aktif', '2026-01-25T08:00:00Z', NOW(), NOW());
INSERT INTO "Act" ("id","actNumber","title","category","description","fileName","fileSize","version","status","lastUpdated","createdAt","updatedAt") VALUES ('act000000000000000000000007', 'Akta 827', 'Akta Perlindungan Data Peribadi 2010', 'Peraturan', 'Mengawal pemprosesan data peribadi individu dan hak individu terhadap data peribadinya.', 'Akta_827_2010.pdf', '1.4 MB', 'Edisi 2024', 'Aktif', '2025-12-10T09:00:00Z', NOW(), NOW());
INSERT INTO "Act" ("id","actNumber","title","category","description","fileName","fileSize","version","status","lastUpdated","createdAt","updatedAt") VALUES ('act000000000000000000000008', 'Akta 759', 'Akta Imigresen 1959/1963', 'Peraturan', 'Mengawal kemasukan dan pergerakan warga asing di Malaysia.', 'Akta_759_1959.pdf', '2.1 MB', 'Edisi 2024', 'Dalam Semakan', '2026-02-18T14:00:00Z', NOW(), NOW());

-- ASIP
INSERT INTO "Asip" ("id","title","referenceNo","description","effectiveDate","fileName","fileSize","status","category","createdAt","updatedAt") VALUES ('asp000000000000000000000001', 'Skim Insurans Pekerjaan — Pampasan Kemalangan', 'ASIP/PK/001/2026', 'Skim pampasan kemalangan kerja bagi pekerja yang mengalami kecederaan dalam masa dan di tempat kerja.', '2026-01-01T00:00:00Z', 'ASIP_Pampasan_Kemalangan.pdf', '1.6 MB', 'Aktif', 'Pampasan', NOW(), NOW());
INSERT INTO "Asip" ("id","title","referenceNo","description","effectiveDate","fileName","fileSize","status","category","createdAt","updatedAt") VALUES ('asp000000000000000000000002', 'Skim Insurans Pekerjaan — Pencen Ilat', 'ASIP/PI/002/2026', 'Skim pencen ilat bagi pekerja yang mengalami kecacatan kekal akibat kemalangan kerja.', '2026-01-01T00:00:00Z', 'ASIP_Pencen_Ilat.pdf', '1.4 MB', 'Aktif', 'Pencen', NOW(), NOW());
INSERT INTO "Asip" ("id","title","referenceNo","description","effectiveDate","fileName","fileSize","status","category","createdAt","updatedAt") VALUES ('asp000000000000000000000003', 'Skim Insurans Pekerjaan — Pencematian', 'ASIP/PM/003/2025', 'Manfaat kematian kepada tanggungan pekerja yang meninggal dunia akibat kemalangan kerja.', '2025-06-01T00:00:00Z', 'ASIP_Pencematian.pdf', '1.1 MB', 'Aktif', 'Manfaat Kematian', NOW(), NOW());
INSERT INTO "Asip" ("id","title","referenceNo","description","effectiveDate","fileName","fileSize","status","category","createdAt","updatedAt") VALUES ('asp000000000000000000000004', 'Skim Insurans Pekerjaan — Bayaran Perubatan', 'ASIP/BP/004/2026', 'Pembayaran perubatan bagi rawatan berkaitan kemalangan kerja atau penyakit pekerjaan.', '2026-01-15T00:00:00Z', 'ASIP_Bayaran_Perubatan.pdf', '2.2 MB', 'Aktif', 'Perubatan', NOW(), NOW());
INSERT INTO "Asip" ("id","title","referenceNo","description","effectiveDate","fileName","fileSize","status","category","createdAt","updatedAt") VALUES ('asp000000000000000000000005', 'Skim Insurans Pekerjaan — Pemulihan Fizio', 'ASIP/PF/005/2025', 'Program pemulihan fizio dan vokasional bagi pekerja yang mengalami kecederaan kerja.', '2025-03-01T00:00:00Z', 'ASIP_Pemulihan.pdf', '1.8 MB', 'Digantikan', 'Pemulihan', NOW(), NOW());
INSERT INTO "Asip" ("id","title","referenceNo","description","effectiveDate","fileName","fileSize","status","category","createdAt","updatedAt") VALUES ('asp000000000000000000000006', 'Skim Insurans Pekerjaan — Faedah Hari Tidak Bekerja', 'ASIP/HTB/006/2026', 'Bayaran ganti bagi hari tidak bekerja akibat cuti sakit berkaitan kemalangan kerja.', '2026-02-01T00:00:00Z', 'ASIP_HTB.pdf', '950 KB', 'Dalam Semakan', 'Bayaran Ganti', NOW(), NOW());

-- SOPs
INSERT INTO "Sop" ("id","title","department","description","procedureSteps","fileName","fileSize","version","approvedBy","dateApproved","status","createdAt","updatedAt") VALUES ('sop000000000000000000000001', 'SOP Tuntutan Pampasan Pekerja', 'Pampasan', 'Prosedur standard pengendalian tuntutan pampasan pekerja berkaitan kemalangan kerja.', '["Pekerja melaporkan kemalangan kepada majikan dalam masa 48 jam.","Majikan mengemukakan borang laporan kemalangan (Borang 21) ke cawangan PERKESO.","Pegawai pampasan menyemak dokumen dan mengeluarkan nombor rujukan tuntutan.","Pemeriksaan perubatan dijalankan oleh panel klinik PERKESO.","Pengesahan tahap kecederaan oleh Lembaga Perubatan.","Keputusan tuntutan dikeluarkan dalam masa 7 hari kerja selepas lengkap dokumen.","Bayaran pampasan diproses dan dikredit ke akaun pekerja dalam 14 hari."]', 'SOP_Pampasan_v2.pdf', '1.2 MB', '2.0', 'Timbalan Pengarah Bahagian Pampasan', '2026-06-20T10:00:00Z', 'Aktif', NOW(), NOW());
INSERT INTO "Sop" ("id","title","department","description","procedureSteps","fileName","fileSize","version","approvedBy","dateApproved","status","createdAt","updatedAt") VALUES ('sop000000000000000000000002', 'SOP Pengurusan Rekod Perubatan', 'Perubatan', 'Pengurusan, penyimpanan, dan pemusnahan rekod perubatan pesakit PERKESO.', '["Semua rekod perubatan direkod dalam Sistem Pengurusan Rekod Perubatan (SPRP).","Rekod fizikal disimpan di ruang arkib berkontrol akses.","Akses kepada rekod terhad kepada pegawai perubatan dan pesakit sahaja.","Rekod disimpan sekurang-kurangnya 7 tahun sebelum dimusnah.","Pemusnahan rekod direkod dalam log pemusnahan dan ditandatangani oleh Pegawai Perubatan Kanan."]', 'SOP_Rekod_Perubatan.pdf', '880 KB', '1.5', 'Pengarah Bahagian Perubatan', '2026-05-10T09:00:00Z', 'Aktif', NOW(), NOW());
INSERT INTO "Sop" ("id","title","department","description","procedureSteps","fileName","fileSize","version","approvedBy","dateApproved","status","createdAt","updatedAt") VALUES ('sop000000000000000000000003', 'SOP Pengesahan Invois Pembekal', 'Kewangan', 'Proses pengesahan dan bayaran invois pembekal PERKESO.', '["Pembekal menghantar invois melalui portal e-Procurement.","Pegawai kewangan menyemak kesahihan dan ketepatan maklumat.","Pegawai kewangan menyemak LPO / kontrak berkaitan.","Pengesahan oleh Ketua Bahagian Kewangan.","Bayaran diproses melalui sistem Gaji & Bayaran (SGB).","Invois ditandai sebagai ''Dibayar'' dalam sistem."]', 'SOP_Invois_Pembekal.pdf', '640 KB', '1.8', 'Pengarah Bahagian Kewangan', '2026-04-15T14:00:00Z', 'Aktif', NOW(), NOW());
INSERT INTO "Sop" ("id","title","department","description","procedureSteps","fileName","fileSize","version","approvedBy","dateApproved","status","createdAt","updatedAt") VALUES ('sop000000000000000000000004', 'SOP Pengurusan Aset ICT', 'ICT', 'Pengurusan kitar hayat aset teknologi maklumat PERKESO.', '["Pendaftaran aset ICT dalam Sistem Pengurusan Aset (SPA) dengan kod unik.","Pelabelan aset dengan nombor siri dan kod inventori.","Pengedaran aset direkod dengan penerima dan lokasi.","Penyenggaraan berkala mengikut jadual tahunan.","Pelupusan aset melalui lelongan / sumbangan dengan kebenaran Lembaga."]', 'SOP_Aset_ICT.pdf', '1.1 MB', '1.2', 'Pengarah Bahagian ICT', '2026-03-08T11:00:00Z', 'Aktif', NOW(), NOW());
INSERT INTO "Sop" ("id","title","department","description","procedureSteps","fileName","fileSize","version","approvedBy","dateApproved","status","createdAt","updatedAt") VALUES ('sop000000000000000000000005', 'SOP Pengambilan Kakitangan Baharu', 'HR', 'Proses pengambilan dan orientasi kakitangan baru PERKESO.', '["Pengiklanan jawatan kosong di portal kerjaya PERKESO.","Penapisan permohonan oleh sistem dan pegawai HR.","Temu duga oleh panel (HR + ketua jabatan).","Pengesahan latar belakang dan pemeriksaan perubatan.","Tawaran jawatan dan penerimaan oleh calon.","Orientasi 3 hari di Ibu Pejabat dan penyerahan kad pengguna."]', 'SOP_Pengambilan_HR.pdf', '780 KB', '2.1', 'Pengarah Bahagian HR', '2026-02-25T09:30:00Z', 'Aktif', NOW(), NOW());
INSERT INTO "Sop" ("id","title","department","description","procedureSteps","fileName","fileSize","version","approvedBy","dateApproved","status","createdAt","updatedAt") VALUES ('sop000000000000000000000006', 'SOP Pengurusan Operasi Cawangan', 'Operasi', 'Prosedur pengurusan operasi harian cawangan PERKESO.', '["Buka cawangan jam 8:00 pagi dan semak sistem POS & LAN.","Pengasingan kaunter mengikut perkhidmatan (Caruman / Pampasan / Perubatan).","Pengurusan barisan dan masa menunggu via sistem QMS.","Pengesahan dokumen pekerja di kaunter.","Penghantaran laporan harian ke Ibu Pejabat sebelum 5:00 petang.","Penutupan cawangan dan backup data pada 5:30 petang."]', 'SOP_Operasi_Cawangan.pdf', '940 KB', '1.4', 'Pengarah Bahagian Operasi', '2026-01-30T08:30:00Z', 'Aktif', NOW(), NOW());

-- Circulars
INSERT INTO "Circular" ("id","circularNo","title","category","summary","content","fileName","fileSize","isMandatory","dateIssued","createdAt","updatedAt") VALUES ('cir000000000000000000000001', 'PKSO/CIR/2026/014', 'Pekeliling Kemas Kini Kadar Caruman Bulanan 2026', 'Korporat', 'Kadar caruman bulanan dikemas kini berkuat kuasa 1 Julai 2026.', 'Berkuat kuasa 1 Julai 2026, kadar caruman bulanan PERKESO dikemas kini mengikut jadual baru (Lampiran A). Semua majikan dikehendaki menggunakan kadar baru bagi semua caruman bulanan Julai 2026 dan seterusnya.', 'Pekeliling_014_2026.pdf', '1.5 MB', true, '2026-06-25T09:00:00Z', NOW(), NOW());
INSERT INTO "Circular" ("id","circularNo","title","category","summary","content","fileName","fileSize","isMandatory","dateIssued","createdAt","updatedAt") VALUES ('cir000000000000000000000002', 'PKSO/CIR/2026/013', 'Pekeliling Penambahbaikan Khidmat Kaunter', 'Operasi', 'Penambahbaikan SOP khidmat kaunter cawangan dengan masa tindak balas ≤ 15 minit.', 'Pekeliling ini menetapkan penambahbaikan khidmat kaunter PERKESO dengan masa tindak balas maksimum 15 minit dan sistem penilaian pelanggan selepas setiap urusan.', 'Pekeliling_013_2026.pdf', '1.1 MB', false, '2026-06-18T10:00:00Z', NOW(), NOW());
INSERT INTO "Circular" ("id","circularNo","title","category","summary","content","fileName","fileSize","isMandatory","dateIssued","createdAt","updatedAt") VALUES ('cir000000000000000000000003', 'PKSO/CIR/2026/012', 'Pekeliling Tatacara Penyimpanan Dokumen Digital', 'ICT', 'Tatacara penyimpanan dokumen digital mengikut polisi retention 7 tahun.', 'Pekeliling ini menetapkan tatacara penyimpanan dan pelupusan dokumen digital PERKESO mengikut polisi retention 7 tahun selaras dengan Akta Arkib Negara 2003.', 'Pekeliling_012_2026.pdf', '1.3 MB', true, '2026-06-10T09:00:00Z', NOW(), NOW());
INSERT INTO "Circular" ("id","circularNo","title","category","summary","content","fileName","fileSize","isMandatory","dateIssued","createdAt","updatedAt") VALUES ('cir000000000000000000000004', 'PKSO/CIR/2026/011', 'Pekeliling Penyelarasan Tuntutan Elaun Perjalanan', 'Kewangan', 'Tuntutan elaun perjalanan mestilah dikemukakan dalam tempoh 30 hari.', 'Mulai 1 Jun 2026, semua tuntutan elaun perjalanan mestilah dikemukakan dalam tempoh 30 hari dari tarikh perjalanan. Tuntutan lewat tidak akan diproses tanpa kelulusan Ketua Bahagian.', 'Pekeliling_011_2026.pdf', '980 KB', true, '2026-05-20T09:00:00Z', NOW(), NOW());
INSERT INTO "Circular" ("id","circularNo","title","category","summary","content","fileName","fileSize","isMandatory","dateIssued","createdAt","updatedAt") VALUES ('cir000000000000000000000005', 'PKSO/CIR/2026/010', 'Pekeliling Hari Bertema Korporat Bulanan', 'HR', 'Hari bertema korporat akan diadakan setiap hari Jumaat pertama setiap bulan.', 'Mulai Julai 2026, hari bertema korporat akan diadakan setiap hari Jumaat pertama setiap bulan. Tema akan diumumkan sebelum tarikh.', 'Pekeliling_010_2026.pdf', '640 KB', false, '2026-05-08T09:00:00Z', NOW(), NOW());
INSERT INTO "Circular" ("id","circularNo","title","category","summary","content","fileName","fileSize","isMandatory","dateIssued","createdAt","updatedAt") VALUES ('cir000000000000000000000006', 'PKSO/CIR/2026/009', 'Pekeliling Polisi Kerja Dalam Talian / WFH', 'HR', 'Polisi kerja dalam talian / WFH dikemas kini dengan pengukuhan protokol keselamatan.', 'Polisi kerja dalam talian / WFH dikemas kini meliputi protokol keselamatan siber, log masuk VPN, dan kekerapan pelaporan.', 'Pekeliling_009_2026.pdf', '1.2 MB', true, '2026-04-15T09:00:00Z', NOW(), NOW());
INSERT INTO "Circular" ("id","circularNo","title","category","summary","content","fileName","fileSize","isMandatory","dateIssued","createdAt","updatedAt") VALUES ('cir000000000000000000000007', 'PKSO/CIR/2026/008', 'Pekeliling Audit Dalaman Suku Tahunan', 'Operasi', 'Audit dalaman suku tahunan akan dijalankan di semua cawangan.', 'Pekeliling ini mengumumkan jadual audit dalaman suku tahunan di semua cawangan PERKESO bermula Q3 2026.', 'Pekeliling_008_2026.pdf', '890 KB', false, '2026-03-22T09:00:00Z', NOW(), NOW());

-- FAQs
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000001', 'Berapakah kadar caruman PERKESO untuk pekerja?', 'Kadar caruman PERKESO ialah 1.75% daripada gaji bulanan pekerja, ditambah dengan 1.75% daripada majikan, menjadikan jumlah 3.5%. Kadar ini berkuat kuasa berkuat kuasa bagi semua pekerja swasta di Malaysia.', 'Caruman', '["kadar","caruman","1.75%"]', NOW(), NOW());
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000002', 'Bagaimana cara saya membuat tuntutan pampasan kemalangan kerja?', 'Anda boleh membuat tuntutan pampasan kemalangan kerja melalui langkah berikut: (1) Laporkan kemalangan kepada majikan dalam 48 jam, (2) Majikan mengemukakan Borang 21 ke cawangan PERKESO, (3) Pemeriksaan perubatan di klinik panel, (4) Tunggu pengesahan Lembaga Perubatan. Proses lengkap biasanya 7-14 hari kerja.', 'Pampasan', '["kemalangan","tuntutan","borang 21"]', NOW(), NOW());
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000003', 'Bagaimana untuk mendaftar pekerja baharu dalam sistem PERKESO?', 'Pendaftaran pekerja baharu boleh dilakukan melalui portal e-Perkeso (https://e-portal.perkeso.gov.my). Majikan perlu log masuk, pilih ''Pendaftaran Pekerja'', dan lengkapkan borang dengan maklumat pekerja. Proses pengesahan biasanya 3-5 hari kerja.', 'Permohonan', '["pendaftaran","pekerja baharu","e-Perkeso"]', NOW(), NOW());
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000004', 'Apakah yang harus saya lakukan jika terlupa kata laluan portal?', 'Jika anda terlupa kata laluan, klik pautan ''Terlupa Kata Laluan'' pada halaman log masuk. Sistem akan menghantar pautan set semula kata laluan ke e-mel berdaftar anda. Pautan sah selama 24 jam.', 'Sistem', '["kata laluan","log masuk","set semula"]', NOW(), NOW());
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000005', 'Di mana saya boleh dapatkan borang tuntutan dan dokumen rasmi PERKESO?', 'Semua borang rasmi PERKESO boleh dimuat turun dari modul SOP, modul Pekeliling, atau modul Akta dalam portal ini. Anda juga boleh menggunakan fungsi Carian Global untuk mencari dokumen tertentu.', 'Sistem', '["borang","dokumen","muat turun"]', NOW(), NOW());
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000006', 'Bagaimana saya tahu status tuntutan saya?', 'Anda boleh menyemak status tuntutan melalui portal e-Perkeso dengan log masuk dan klik ''Status Tuntutan''. Sistem akan memaparkan peringkat pemprosesan terkini, jangkaan masa, dan pegawai yang mengendali.', 'Pampasan', '["status","tuntutan","e-Perkeso"]', NOW(), NOW());
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000007', 'Apakah jenis penyakit yang dilindungi oleh Skim Insurans Pekerjaan?', 'Skim Insurans Pekerjaan (SIP) melindungi penyakit pekerjaan seperti penyakit kulit akibat bahan kimia, pendengaran terjejas akibat bunyi bising, dan penyakit paru-paru akibat habuk. Senarai penuh 39 penyakit pekerjaan boleh didapati dalam Jadual Akta 799.', 'Pampasan', '["penyakit","SIP","pekerjaan"]', NOW(), NOW());
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000008', 'Bagaimana cara mengemas kini maklumat peribadi dalam rekod PERKESO?', 'Pekerja boleh mengemas kini maklumat peribadi melalui portal e-Perkeso. Pilih ''Profil Saya'', klik ''Kemas Kini'', dan hantar permohonan. Kemas kini akan diambil tindakan dalam 3-5 hari kerja oleh cawangan berdekatan.', 'Sistem', '["profil","kemas kini","maklumat"]', NOW(), NOW());
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000009', 'Apakah skim pemulihan vokasional yang disediakan?', 'PERKESO menyediakan skim pemulihan vokasional bagi pekerja yang mengalami kecacatan akibat kemalangan kerja. Skim ini termasuk latihan semula, bantuan kerja, dan modifikasi tempat kerja. Permohonan melalui pegawai pampasan cawangan berdekatan.', 'Pampasan', '["pemulihan","vokasional","kecacatan"]', NOW(), NOW());
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000010', 'Bagaimana cara mengemukakan aduan mengenai khidmat PERKESO?', 'Aduan boleh dikemukakan melalui: (1) Borang Aduan di kaunter, (2) E-mel ke aduan@perkeso.gov.my, (3) Sistem Aduan Dalam Talian dalam portal e-Perkeso, atau (4) Hotline 1-300-22-8000. Setiap aduan akan menerima nombor rujukan untuk pengesanan.', 'Sistem', '["aduan","khidmat","hotline"]', NOW(), NOW());
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000011', 'Berapakah had maksimum pampasan kemalangan kerja?', 'Had maksimum pampasan bergantung pada jenis dan tahap kecederaan. Untuk kecacatan kekal, pampasan boleh mencecah sehingga RM70,000 (pencen ilat) atau bayaran jumlah pukul. Bagi kematian, tanggungan akan menerima pencemaran dan faedah penjagaan anak.', 'Pampasan', '["had","maksimum","pampasan"]', NOW(), NOW());
INSERT INTO "Faq" ("id","question","answer","category","tags","createdAt","updatedAt") VALUES ('faq000000000000000000000012', 'Apakah syarat kelayakan untuk menerima faedah PERKESO?', 'Pekerja layak menerima faedah PERKESO jika: (1) Bekerja di bawah kontrak perkhidmatan, (2) Berumur 16-80 tahun, (3) Membayar caruman bulanan secara berkala. Pekerja kontrak, sambilan, dan sementara juga dilindungi.', 'Caruman', '["kelayakan","syarat","faedah"]', NOW(), NOW());

-- Notifications
INSERT INTO "Notification" ("id","userId","title","message","type","module","isRead","createdAt") VALUES ('ntf000000000000000000000001', 'usr000000000000000000000002', 'Pengumuman Baharu', 'Pengumuman Hari Kebangsaan PERKESO 2026 telah diumumkan.', 'info', 'Announcement', false, '2026-07-25T09:00:00Z');
INSERT INTO "Notification" ("id","userId","title","message","type","module","isRead","createdAt") VALUES ('ntf000000000000000000000002', 'usr000000000000000000000002', 'Pekeliling Wajib', 'Pekeliling Kemas Kini Kadar Caruman Bulanan 2026 — wajib dibaca.', 'critical', 'Circular', false, '2026-07-24T08:00:00Z');
INSERT INTO "Notification" ("id","userId","title","message","type","module","isRead","createdAt") VALUES ('ntf000000000000000000000003', 'usr000000000000000000000002', 'SOP Dikemas Kini', 'SOP Tuntutan Pampasan Pekerja dikemas kini ke versi 2.0.', 'info', 'SOP', false, '2026-07-22T10:00:00Z');
INSERT INTO "Notification" ("id","userId","title","message","type","module","isRead","createdAt") VALUES ('ntf000000000000000000000004', 'usr000000000000000000000002', 'Amaran Keselamatan', 'E-mel phishing berpura-pura PERKESO — sila ambil perhatian.', 'warning', 'Announcement', true, '2026-07-19T10:30:00Z');
INSERT INTO "Notification" ("id","userId","title","message","type","module","isRead","createdAt") VALUES ('ntf000000000000000000000005', 'usr000000000000000000000002', 'Aktiviti Korporat', 'Pertandingan Inovasi Kakitangan 2026 dibuka untuk pendaftaran.', 'success', 'Announcement', true, '2026-07-10T09:30:00Z');
INSERT INTO "Notification" ("id","userId","title","message","type","module","isRead","createdAt") VALUES ('ntf000000000000000000000006', 'usr000000000000000000000001', 'Pengumuman Berjaya Diterbitkan', 'Pengumuman ''Hari Kebangsaan PERKESO 2026'' telah disemat ke dashboard.', 'success', 'Announcement', false, '2026-07-25T09:05:00Z');
INSERT INTO "Notification" ("id","userId","title","message","type","module","isRead","createdAt") VALUES ('ntf000000000000000000000007', 'usr000000000000000000000001', 'Pengguna Baharu Didaftarkan', 'Siti Noor Aishah telah didaftarkan ke sistem.', 'info', 'User', false, '2026-07-23T08:00:00Z');
INSERT INTO "Notification" ("id","userId","title","message","type","module","isRead","createdAt") VALUES ('ntf000000000000000000000008', 'usr000000000000000000000001', 'Pekeliling Wajib', 'Pekeliling 014/2026 ditandai wajib untuk semua cawangan.', 'warning', 'Circular', true, '2026-06-25T09:30:00Z');

COMMIT;

-- Seed complete. Verify with: SELECT COUNT(*) FROM "User";